language: scala

sudo: required

scala:
  - "2.11.8"

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

services:
  - rabbitmq
  - cassandra

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m +test

deploy:
  provider: script
  script:
    # do the maven central sync only once, as all of the artifacts are under the same bintray package
    - sbt -J-XX:ReservedCodeCacheSize=128m +publish amqp/bintraySyncMavenCentral
  on:
    tags: true
    repo: akka/alpakka

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "DLc1v2XMWrxtbPzVfoArkSQiwzT+O7/rwT7APqoA68K5A1pwxDw5BD3sOLpd6rKbPBulmwDAAQ1am3uE6lbmymCTMe8bvA3iHWy0Jg8baK4nC46EKFLabQz4Uaoq/bs92YGW1QH12rbBPyTA7uvPpvhmb8uyUbJqjT3uyROqHhHfhll89dsPVaK0NCY9DN2K356M87z7cp1SvtfAiF8qaNjNmlOfWjIEUSO1SiiqQBjT/GJvhrrW32J4htf5CqEEYBSoN+fqTCwwdo3GpOFFq+Zh5TSoyvKyi5xo+LVq0hW2SAYTHMMB5WhLd1cvQ0bvK6FpUhyfMcON/8ad3R7paNVxLpIGEu8hsUYGsENjdXaEK4g1TurDeVekWJRYyGMCmy2cCg5yHC+Pb56qOgpM7gmZACCitLap1jXUCWI27q+7cvxuxaBb6EPiDuWGNQXHH+OkbD/s4RJO3kQfv1Si64RON8+bZ+fqOWLK+BuakYi3YMukFgPngQozX3aMZOVcEBKJZtquwewCKsNV2VGItJxrp3MDol0HhuNvdUvIf5UydZZCyJTo1DBsK49yDUj7iKOEJk5Qc5oYfEhSEKcGRZs8Yl9n/kIJUh8ZYTT+35rwD27dHgsEkPkCEGpbMP/r0JewkWH7q9FfajPIYOlEpoP6tCsdP4mBOyF1uZH7omM="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "gasjgT+qHUFPe/eMqvwD7WtzQmNw++LXmmQ6ic6VJOf/drAQckdeXIaa3rOsuoiI72xtngIUPil61+bviRf3Qgw061w65dSlrn4Pm1c4f4kOCRBQCpsg06PK2Xs40ZD/9l9e+3N0T6alwx//PFH+bUB5yEi7y/Qs1dOKtofvvtoTkGvF6GZDCMiKwpYmcEKmBbmEuyaFLd5h1N6oJ53g7dtyh1KD9gU4HXmc3QujrKSxm3YunMf68wgtTJWZf3b/OcyVTSz7/8mbvJ++GWCyVK5B8snAnKxwSNHhYysNdOoOTGhwF2dnE38Vr/NXldHnm+M2LzuBBADXLmxlW92bxv+IjuAT+HtBoPEP9I+f/eJqfirkrMRWiylWN7zcchMzHTHS54qx1JvtRyJYNFsOfzqLry/IUZoT/1tLe2vPCRE601K5pS2GEDAt/gj3BTCWpCvidgXXq4KPlj5IqeIJ5UVWSpjCCH0hZUwuUUwgSNTXFg7Ug+U4U5DjPmyla5oNj9d+RIGqWtsixB8QAs5dCgtBa0om/f8nT584iHjrpvduLpoUpUcMPyPgcJnlHNvKawnEW0JCcMxR4fJBsG3IG+6Q6Rbo17VIs/Z5hgcNQtJMVnjiIGfOFBQKYKrStAWlJWK9WTo5L5oO3sn+BZQUnuJxafoJsdArEogzfbRjovk="
    # encrypt with: travis encrypt SONATYPE_USER=...
    - secure: "qRXS//WtSBOSiEpQ2VXB9m9C8jaj3NmAm8hkF9ufvB5KEiKteHK8Zll2+XQWdLgb2At1T7LR/hXe6Hv1lXuUXIMOzfkanUI+bn5PkqQNiBqYzJBUrNzraSi5ZiMlYKc/lEjMyXzb0lLJGVhJn3nQHbauhQ3RIpAbMb3qnSzJDV6jMWnWwmn3GjHF9cUPbw3Gtu73IgEI3aFofOfd3WKE0crOK+N+OWLgxEJx9Ole0I3CXdbRLGGiMNHjQ7zm0Rf4zD7Pa4qpMQzF5DO43OxN20WtT82uYD8/uWZz3QTasG3Qbx2pShPB2rZbi85HQBijW0GAQS3etMV6xggZckzmbmtufZ3D8k6CuLS0jp5WBxWwhuFmEu1FAydMNuGlXBkTODqKcwzyXwa5iYzq/lPeOh9W1F+3Jr5D5x0PHYk6MLS/KQ8nSe0Wmge2Iro1JTcVwxktXW3NQDxC58nh64pUVC7XcS+0eX6LgnBjmNdJ9D65tKx0qy4tfOEtAgulybYmQefB+91ct6YVB9fIIbQdtEk6L8XTw58cliI+2mj2d6/Nr6v8uWpGWjzsgrdtXs+qsYsIMrYs6xSAZcBL1oLjY11/1E3IdJOdcK6eUkw2ms3rwK67El5oQjfq5AlAc9Y+n0Rdx3ABeXs2TYUfiF/075cmfbF/KZxzSliMQmeD/iQ="
    # encrypt with: travis encrypt SONATYPE_PASS=...
    - secure: "GqxKeUiBHtALLyu1Q46OfgnkMHg9BiixsJ3dQwr5e0p/QH/J/aGv7BdIa/sT5zCzcY5tgRXuGhO2BCY5T9yapZnvcaC8P5d+Kxmud8/KE9TZ2u6qpFK5tvWr9elP7wqPNU76eo+4EACv6zzwvMJ78nXtwrSzyXxrYIJmIL4QS8CnxnWL7InhsPqF7dVWYsvHXjE6cm4gvaqPvO78x0bOEXLMBtQXr6PMiXL58IQvm9mwqHd4VsTfCQ42kx3Kt3eXbtBH+7162FTqOxUt5S9wHLa1kryA1TZDznwwss5WnHnz7uogb/rIvYkvIRRj42lLTGsrQuN2YFLf0+GnL1reHnaraOjBWTN75C1HUhZoVZFcRjXPewYGMoJjZezli/uUOJGGzYeyWRsX4ebpKLEPb6FA9LabP4EXxAEcEJDG/InzMbdbI8UG9GKqeXlnrFUq3OG4Hn6qQXqcr93W6QNV9NADH665a7GjCbmOVnYUaShVegwcjodzstVeYCXb7V6que1opt4jKsapur+MAokNBtayKQISSBs+ymCysVHlWxGvNhYR44ddiCsTVvLl8JhDqN6OEWaKpaXsBEiQorBTtrkexkM8HuLJ40KuZPUvQSuVR9I/nUlzRCxjnxoUI+9B2FfasyEvT9Ci/MCj/OAF/tDVZ3qylscjlijhrFo/7uU="
